# config.yaml
# Central configuration for the Horse ID pipeline.

# --- File and Directory Paths ---
# Use {data_root} as a placeholder to keep paths relative and clean.
paths:
  data_root: "~/google-drive/horseID Project/data-sandbox"
  dataset_dir: "/Users/dleigh/google-drive/horseID Project/data/horse_photos"
  manifest_file: "{data_root}/horse_photos_manifest.csv"
  # Directory for pre-trained models and calibrations
  calibration_dir: "{data_root}/calibrations"
  temp_dir: "{data_root}/tmp"
  features_dir: "{data_root}/features"
  # Output file for the merged manifest
  merged_manifest_file: "{data_root}/horse_photos_manifest_merged.csv"
  merge_results_file: "{data_root}/merge_results.csv" # Renamed from similarity_log_file
  predictions_file: "{data_root}/prediction_results.html"

# --- Gmail API Settings ---
gmail:
  token_file: "token.json"
  credentials_file: "credentials.json"
  scopes: ['https://www.googleapis.com/auth/gmail.readonly']

# --- Multi Horse Detector Settings ---
detection:
  #yolo_model: 'yolov8n-seg.pt' # Options: yolov5s, yolov5m, yolov5l, yolov5x
  yolo_model: 'yolo11x-seg.pt' 
  confidence_threshold: 0.1
  # If multiple horses are detected, but one is significantly larger than others,
  # consider it a single primary detection. e.g., 2.0 means twice as large.
  size_ratio_for_single_horse: 2.2
  # The detector will read from manifest_file and write to this file
  detected_manifest_file: "{data_root}/horse_photos_manifest_detected.csv"


# --- Similarity/Merging Settings ---
similarity:
  # The threshold for determining if two groups of photos represent the same horse.
  # A lower value means more likely to merge (less sensitive to differences).
  merge_threshold: 0.203
  # The merge script will read from the detected_manifest_file.
  # This ensures it only works on data that has been processed by the detector.
  inference_threshold: 0.8

# --- S3 Settings ---
s3:
  bucket_name: "horse-id-data" # Replace with your actual S3 bucket name