FROM public.ecr.aws/lambda/python:3.13

WORKDIR /var/task

COPY responder-requirements.txt .
RUN pip install -r responder-requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY webhook_responder.py ${LAMBDA_TASK_ROOT}/

# Set the CMD to the new handler
CMD [ "webhook_responder.webhook_handler" ]